### ISSUE TITLE
Sort by type before sort by contributor?

### ISSUE THREAD

**Issue by cibvia** [a2ohm/csbernardins#1]
Est-ce intentionnel de trier la bibliographie par type de document avant de trier par auteur ?
https://github.com/a2ohm/csbernardins/blob/c5ebc16c6bccb2f8021eb5eb709b87db3be2023e/college-des-bernardins.csl#L693
https://github.com/a2ohm/csbernardins/blob/c5ebc16c6bccb2f8021eb5eb709b87db3be2023e/college-des-bernardins.csl#L694

Je m'attendais à avoir une liste alphabétique et j'ai été surpris par le résultat.
![image](https://user-images.githubusercontent.com/15103269/144293449-37874343-af5b-4cc0-8496-85873799bdb8.png)

Si c'est intentionnel, ne faudrait-il pas alors séparer clairement les catégories de documents entre elles ?

**Comment by a2ohm** [comment]
Bien vu, merci @cibvia !
